scotgov-report.pdf: scotgov-report.tex 24GHz.tex lasers.tex
	xelatex -interaction=nonstopmode scotgov-report.tex
	xelatex -interaction=nonstopmode scotgov-report.tex
	xelatex -interaction=nonstopmode scotgov-report.tex
