scotgov-report.pdf: scotgov-report.tex 24GHz.tex lasers.tex literature.bib
	xelatex -interaction=nonstopmode scotgov-report.tex
	biber scotgov-report
	xelatex -interaction=nonstopmode scotgov-report.tex
	xelatex -interaction=nonstopmode scotgov-report.tex
